### ISSUE TITLE
Quero ajuda

### ISSUE THREAD

**Issue by alissonandrade2020** [juakacc/olivedos-covid#1]
como faço para rodar o projeto e tenho outra dúvida também, quero pegar de outra cidade o resultados como faço ????

**Comment by juakacc** [comment]
Hello,

Clone repository: 

```shell
git clone https://github.com/juakacc/olivedos-covid.git
cd olivedos-covid
```
If you don't have gatsby installed: 
```shell
npm install -g gatsby-cli
```
Install dependencies 
```shell
npm i
```
Run project
```shell
gatsby develop
```

To get data from another city there is possibility in the api itself. Here [Brasil.io](https://brasil.io/dataset/covid19/caso_full/)

**Comment by alissonandrade2020** [comment]
Me ajuda ai.

a da minha cidade: https://brasil.io/dataset/covid19/caso_full/?search=Salgado+de+S%C3%A3o+F%C3%A9lix&epidemiological_week=&date=&order_for_place=&state=PB&city=&city_ibge_code=&place_type=&last_available_date=&is_last=&is_repeated=

**Comment by juakacc** [comment]
Search the code of city in ibge site, and do request:
```
https://brasil.io/api/dataset/covid19/caso/data/?is_last=True&city_ibge_code=?
```
